name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        id: build
        run: |
          npm i
          npm run build

      - name: Upload
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
